error_on_line_overflow = false
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
max_width = 140
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
trailing_comma = "Never"